CROSS_PREFIX ?= aarch64-linux-gnu-

CFLAGS += -mgeneral-regs-only

includes += -Iarch/arm64/include

objs += arch/arm64/cpu.o
objs += arch/arm64/boot.o
objs += arch/arm64/interrupts.o
objs += arch/arm64/memory.o
objs += arch/arm64/thread.o
objs += drivers/uart/pl011.o
