CFLAGS += -mno-sse
LDFLAGS += -n

includes += -Iarch/x86/include

objs += arch/x86/cpu.o
objs += arch/x86/boot.o
objs += arch/x86/entry.o
objs += arch/x86/exceptions.o
objs += arch/x86/multiboot_header.o
objs += arch/x86/thread.o
objs += drivers/uart/8250.o
