#!/bin/bash

set -e

. /etc/os-release

if [ "$ID" = "fedora" ]; then
    sudo dnf install gcc xorriso
elif [ "$ID" = "ubuntu" ]; then
    sudo apt install --yes curl grub-pc-bin cmake
elif [ "$ID" = "antergos" ] || [ "$ID" = "arch" ]; then
    sudo pacman -S --noconfirm curl cmake grub mtools
else
    echo "Warning: '$ID' is not a supported OS."
fi

toolchain=nightly-2019-04-18

# Please hote that the rustup script modifies PATH environment variable.
curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $toolchain

source $HOME/.cargo/env

rustup install $toolchain
rustup default $toolchain
rustup component add rust-src

cargo install xargo
